### ISSUE TITLE
Enabling learn_weights in model_params.yaml throws errors.

### ISSUE THREAD

**Issue by prateekdhawalia** [danbider/lightning-pose#60]
Enabling learn_weights in model_params.yaml throws errors
learn_weights: True

Variable naming issue in factory.py

**Comment by themattinthehatt** [comment]
Thanks, apologies for the new bug. I'll fix this later today. I should mention that we played around with learning the weights on the unsupervised losses some months ago, but were not able to get it to outperform grid searching (which of course is more computationally expensive). We've made a lot of updates to the code since then, some of which may make the learning of weights more feasible, but have not gone back to retest this feature. If you end up getting something useful out of it please let us know! 

We've generally found that weights in the range of 4-6 are good for a range of datasets and losses, so that could be a good place for you to at least start the weights (whether learning from there or not).

**Comment by prateekdhawalia** [comment]
@themattinthehatt Thanks for the update on learning weights for unsupervised losses.
I did not understand this part "We've generally found that weights in the range of 4-6 are good for a range of datasets and losses, so that could be a good place for you to at least start the weights".
Can you elaborate this, so that I can explore it?

**Comment by themattinthehatt** [comment]
@prateekdhawalia the bug that you highlighted is now fixed (on the latest `develop` branch), so you can technically learn the weights if you want to. However, I tried this feature again on our test dataset and got bad results, so I would still not recommend it.

Regarding exploration of the weights, these values are set in the config file under "losses". So, for example, if you want to train a pca_singleview model with a weight of 5, you could run
```
$ python scripts/train_hydra.py 'model.losses_to_use=[pca_singleview]' losses.pca_singleview.log_weight=5.0
```

* note 1: the single quotes around model.losses_to_use ensure the square brackets are processed correctly
* note 2: this weight is actually the log of the weight used in the final objective function, so small differences in these values matter

To perform hyperparameter searches you can use hydra's very convenient `multirun` feature (https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run/); below is a common hyperparameter search that we perform (for the weights on the pca_singleview loss):
```
$ python scripts/train_hydra.py --multirun 'model.losses_to_use=[pca_singleview]' losses.pca_singleview.log_weight=3.0,4.0,5.0,6.0,7.0,8.0
```
You can then review the results using the tracking-diagnostics package that I mentioned here: https://github.com/danbider/lightning-pose/issues/59#issuecomment-1238547822
