### ISSUE TITLE
dependency on fixed image size

### ISSUE THREAD

**Issue by thejanzimmermann** [danbider/lightning-pose#86]
Hi there, amazing work. I am wondering how vital the dependency on fixed image sizes for training your setup is. Reading the code it seems you are currently requiring a fixed image size but DALIs transform module should be able to scale dynamically.

Best

Jan

**Comment by themattinthehatt** [comment]
hey @thejanzimmermann, thanks for checking out the repo! Currently we do require fixed image sizes; this was a design choice we made early on because our datasets did not contain images of different sizes. It's not conceptually crucial that image sizes are fixed, but it would require a bit of work to generalize this in the repo. Are you working with multiple image sizes in a single dataset?

**Comment by thejanzimmermann** [comment]
Thanks so much. For training yes. Our use cases are usually cropped images and since our arenas are large a fixed size makes it difficult.
________________________________

**Comment by themattinthehatt** [comment]
@thejanzimmermann are you interested in trying lightning pose out on your data? We don't have the bandwidth at the moment to support this feature (though we'd like to in the future), but if you'd like to try it yourself we'd be happy to meet and talk about what would be necessary for a PR.

**Comment by danbider** [comment]
@thejanzimmermann how does your data look like? labeled images of different shapes? or unlabeled videos of different shapes? or both? we're well aware of your work and it'll be cool to collaborate with you here a bit.

in principle, this requirement could be dropped -- we do all of the meaningful computations on the resized image shapes (and resizing happens on the fly). But fixing it needs the careful attention that we don't currently have...

videos are assumed to have the same shape so that we could undo the data augmentation and compute our unsupervised losses in the unified resized image shape (orig image dims parameter could be dropped too if we dynamically keep track of video size in DALI).

I think that a PR here will need to track the original image shapes both in 1) imgaug labeled frame loading , 2) DALI unlabeled video loading, and in `model.predict_step()`.

another simple option (just to know if lightning-pose is worth your time): you can preprocess the images and labels; resize the images and keypoint labels to a standard size, and train.

**Comment by themattinthehatt** [comment]
closed by #117
